/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zenatti.vinicius.cupommaker;
import java.awt.*;
import java.awt.print.*;

/**
 *
 * @author vini
 */
public class OptionsTela extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OptionsTela.class.getName());

    /**
     * Creates new form OptionsTela
     */
    public OptionsTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NomeCheckBox = new javax.swing.JCheckBox();
        EmailCheckBox = new javax.swing.JCheckBox();
        SenhaCheckBox = new javax.swing.JCheckBox();
        CpfCheckBox = new javax.swing.JCheckBox();
        TelefoneCheckBox = new javax.swing.JCheckBox();
        SenhaGovCheckBox = new javax.swing.JCheckBox();
        SenhaGovTextField = new javax.swing.JTextField();
        NomeTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        SenhaTextField = new javax.swing.JTextField();
        CpfTextField = new javax.swing.JTextField();
        TelefoneTextField = new javax.swing.JTextField();
        printButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NomeCheckBox.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        NomeCheckBox.setText("Nome");
        NomeCheckBox.addActionListener(this::NomeCheckBoxActionPerformed);

        EmailCheckBox.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        EmailCheckBox.setText("Email");
        EmailCheckBox.addActionListener(this::EmailCheckBoxActionPerformed);

        SenhaCheckBox.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        SenhaCheckBox.setText("Senha");
        SenhaCheckBox.addActionListener(this::SenhaCheckBoxActionPerformed);

        CpfCheckBox.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        CpfCheckBox.setText("CPF");
        CpfCheckBox.addActionListener(this::CpfCheckBoxActionPerformed);

        TelefoneCheckBox.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        TelefoneCheckBox.setText("Telefone");
        TelefoneCheckBox.addActionListener(this::TelefoneCheckBoxActionPerformed);

        SenhaGovCheckBox.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        SenhaGovCheckBox.setText("Senha Gov");
        SenhaGovCheckBox.addActionListener(this::SenhaGovCheckBoxActionPerformed);

        SenhaGovTextField.setEnabled(false);

        NomeTextField.setEnabled(false);

        EmailTextField.setEnabled(false);

        SenhaTextField.setEnabled(false);

        CpfTextField.setEnabled(false);

        TelefoneTextField.setEnabled(false);

        printButton.setText("Imprimir");
        printButton.addActionListener(this::printButtonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(printButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SenhaGovCheckBox)
                            .addComponent(NomeCheckBox)
                            .addComponent(EmailCheckBox)
                            .addComponent(SenhaCheckBox)
                            .addComponent(CpfCheckBox)
                            .addComponent(TelefoneCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TelefoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SenhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SenhaGovTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeCheckBox)
                    .addComponent(NomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailCheckBox)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SenhaCheckBox)
                    .addComponent(SenhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CpfCheckBox)
                    .addComponent(CpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefoneCheckBox)
                    .addComponent(TelefoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SenhaGovCheckBox)
                    .addComponent(SenhaGovTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(printButton)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SenhaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaCheckBoxActionPerformed
        if(SenhaCheckBox.isSelected()){
            SenhaTextField.setEnabled(true);
        }else{
            SenhaTextField.setEnabled(false);
        }
    }//GEN-LAST:event_SenhaCheckBoxActionPerformed

    private void CpfCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CpfCheckBoxActionPerformed
        if(CpfCheckBox.isSelected()){
            CpfTextField.setEnabled(true);
        }else{
            CpfTextField.setEnabled(false);
        }
    }//GEN-LAST:event_CpfCheckBoxActionPerformed

    private void TelefoneCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefoneCheckBoxActionPerformed
        if(TelefoneCheckBox.isSelected()){
            TelefoneTextField.setEnabled(true);
        }else{
            TelefoneTextField.setEnabled(false);
        }
    }//GEN-LAST:event_TelefoneCheckBoxActionPerformed

    private void SenhaGovCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaGovCheckBoxActionPerformed
        if(SenhaGovCheckBox.isSelected()){
            SenhaGovTextField.setEnabled(true);
        }else{
            SenhaGovTextField.setEnabled(false);
        }
        
    }//GEN-LAST:event_SenhaGovCheckBoxActionPerformed

    private void NomeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeCheckBoxActionPerformed
        if(NomeCheckBox.isSelected()){
            NomeTextField.setEnabled(true);
        }else{
            NomeTextField.setEnabled(false);
        }
    }//GEN-LAST:event_NomeCheckBoxActionPerformed

    private void EmailCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailCheckBoxActionPerformed
        // TODO add your handling code here:
        if(EmailCheckBox.isSelected()){
            EmailTextField.setEnabled(true);
        }else{
            EmailTextField.setEnabled(false);
        }
    }//GEN-LAST:event_EmailCheckBoxActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        Cupom cupom = new Cupom();
     
        if(NomeCheckBox.isSelected()){
            String e = "Nome : " + NomeTextField.getText();
            cupom.addItem(e);
        }
        
    if (CpfCheckBox.isSelected()) {
            String e = "CPF : " + CpfTextField.getText();
            cupom.addItem(e);
        }

    if (EmailCheckBox.isSelected()) {
        String e = "Email : " + EmailTextField.getText();
        cupom.addItem(e);
    }


    if (SenhaCheckBox.isSelected()) {
        String e = "Senha : " + SenhaTextField.getText();
        cupom.addItem(e);
    }

    if (SenhaGovCheckBox.isSelected()) {
        String e = "Senha Gov : " + SenhaGovTextField.getText();
        cupom.addItem(e);
    }

    if (TelefoneCheckBox.isSelected()) {
        String e = "Telefone : " + TelefoneTextField.getText();
        cupom.addItem(e);
    }
        imprimir(cupom);
    }//GEN-LAST:event_printButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OptionsTela().setVisible(true));
    }

    public void imprimir(Cupom cupom) {
        PrinterJob job = PrinterJob.getPrinterJob();

        job.setPrintable(new Printable() {
            @Override
            public int print(Graphics g, PageFormat pf, int pageIndex) throws PrinterException {
                if (pageIndex > 0) {
                    return NO_SUCH_PAGE;
                }

                Graphics2D g2d = (Graphics2D) g;
                g2d.translate(pf.getImageableX(), pf.getImageableY());

                g.setFont(new Font("Monospaced", Font.PLAIN, 18));

                String texto = cupom.generateText();
                String[] linhas = texto.split("\n");

                int y = 15;
                for (String linha : linhas) {
                    g.drawString(linha, 0, y);
                    y += 15;
                }

                return PAGE_EXISTS;
            }
        });

        if (job.printDialog()) {
            try {
                job.print();
            } catch (PrinterException e) {
                e.printStackTrace();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CpfCheckBox;
    private javax.swing.JTextField CpfTextField;
    private javax.swing.JCheckBox EmailCheckBox;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JCheckBox NomeCheckBox;
    private javax.swing.JTextField NomeTextField;
    private javax.swing.JCheckBox SenhaCheckBox;
    private javax.swing.JCheckBox SenhaGovCheckBox;
    private javax.swing.JTextField SenhaGovTextField;
    private javax.swing.JTextField SenhaTextField;
    private javax.swing.JCheckBox TelefoneCheckBox;
    private javax.swing.JTextField TelefoneTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton printButton;
    // End of variables declaration//GEN-END:variables
}
